### ISSUE TITLE
Assignment 1.2 

### ISSUE THREAD

**Issue by kiran-ta-official** [kiran-ta-official/mle-training#1]
## TASK SUMMARY
- [ ] Create new branch and push ML code with README file, with commit msgs.
- [ ] Add .gitignore file to ignore pyc files and the CSV data files.
- [ ] Create conda env : mle-dev, export env file as env.yml and commit the file.
- [ ] Update the README file with instructions on how to run the code.
- [ ] Create a Pull Request (PR). Link the PR to the issue.
- [ ] Add collaborators and request a PR.
